name: tracelet_platform_interface
description: >-
  A common platform interface for the Tracelet background geolocation plugin.
  Used by tracelet_android and tracelet_ios implementations.
version: 0.1.0
homepage: https://github.com/Ikolvi/Tracelet
repository: https://github.com/Ikolvi/Tracelet/tree/main/packages/tracelet_platform_interface
issue_tracker: https://github.com/Ikolvi/Tracelet/issues

environment:
  sdk: ^3.10.3
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  collection: ^1.18.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^22.7.0
