name: tracelet_android
description: Android implementation of the Tracelet background geolocation plugin.
version: 0.1.0
homepage: https://ikolvi.com
repository: https://ikolvi.com/tree/main/packages/tracelet_android

environment:
  sdk: ^3.10.3
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  tracelet_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: tracelet
    platforms:
      android:
        package: com.tracelet.tracelet_android
        pluginClass: TraceletAndroidPlugin
        dartPluginClass: TraceletAndroid
